export const clothes = [
  {
    id: "zapato1",
    name: "h-zapato1",
    description: "Zapatos",
    type: "h",
    precio: "$ 100.000",
  },
  {
    id: "zapato2",
    name: "h-zapato2",
    description: "Zapatos",
    type: "h",
    precio: "$ 120.000",
  },
  {
    id: "zapato3",
    name: "h-zapato3",
    description: "Zapatos",
    type: "h",
    precio: "$ 115.000",
  },
  {
    id: "zapato4",
    name: "h-zapato4",
    description: "Zapatos",
    type: "h",
    precio: "$ 90.000",
  },
  {
    id: "traje1",
    name: "h-traje1",
    description: "Traje",
    type: "h",
    precio: "$ 180.000",
  },
  {
    id: "traje2",
    name: "h-traje2",
    description: "Traje",
    type: "h",
    precio: "$ 200.000",
  },
  {
    id: "traje3",
    name: "h-traje3",
    description: "Traje",
    type: "h",
    precio: "$ 250.000",
  },
  {
    id: "traje4",
    name: "h-traje4",
    description: "Traje",
    type: "h",
    precio: "$ 230.000",
  },
  {
    id: "vestido1",
    name: "m-vestido1",
    description: "Vestido",
    type: "m",
    precio: "$ 50.000",
  },
  {
    id: "vestido2",
    name: "m-vestido2",
    description: "Vestido",
    type: "m",
    precio: "$ 40.000",
  },
  {
    id: "vestido3",
    name: "m-vestido3",
    description: "Vestido",
    type: "m",
    precio: "$ 75.000",
  },
  {
    id: "vestido4",
    name: "m-vestido4",
    description: "Vestido",
    type: "m",
    precio: "$ 55.000",
  },
  {
    id: "vestido5",
    name: "m-vestido5",
    description: "Vestido",
    type: "m",
    precio: "$ 35.000",
  },
  {
    id: "zapato1",
    name: "m-zapato1",
    description: "Zapato",
    type: "m",
    precio: "$ 110.000",
  },
  {
    id: "zapato2",
    name: "m-zapato2",
    description: "Zapato",
    type: "m",
    precio: "$ 130.000",
  },
  {
    id: "zapato3",
    name: "m-zapato3",
    description: "Zapato",
    type: "m",
    precio: "$ 115.000",
  },
  {
    id: "zapato4",
    name: "m-zapato4",
    description: "Zapato",
    type: "m",
    precio: "$ 175.000",
  },
];
